# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a89f4987ffd1b2a7c988f9e7b6d664f73786f6be19eecd4de2fe298750af4c16d586cc5957696b31b379abd66ad79a6781b057cd1e5d56da179e6b60b2edf535

test:
  secret_key_base: d222dc5cc709711f174327c9834485b852ffdf95042dd022f1e13a9e37a205eaa6b29ca01e711ed0d8615fa096097a8539d57e9422553817a320c4bbf630b060

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
